/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mockSilentErc20Sol from "./MockSilentERC20.sol";
export { MockERC20__factory } from "./MockERC20__factory";
