/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { Recorder, RecorderInterface } from "../../src/Recorder";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "withdrawalKeyHash",
        type: "bytes",
      },
    ],
    name: "withdrawals",
    outputs: [
      {
        internalType: "uint256",
        name: "amountWithdrawn",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class Recorder__factory {
  static readonly abi = _abi;
  static createInterface(): RecorderInterface {
    return new Interface(_abi) as RecorderInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Recorder {
    return new Contract(address, _abi, runner) as unknown as Recorder;
  }
}
