/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface RecorderInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "depositCountForAmount"
      | "leaves"
      | "withdrawalCountForAmount"
      | "withdrawals"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "depositCountForAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "leaves", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "withdrawalCountForAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawals",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "depositCountForAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "leaves", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawalCountForAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawals",
    data: BytesLike
  ): Result;
}

export interface Recorder extends BaseContract {
  connect(runner?: ContractRunner | null): Recorder;
  waitForDeployment(): Promise<this>;

  interface: RecorderInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  depositCountForAmount: TypedContractMethod<
    [amount: BigNumberish],
    [bigint],
    "view"
  >;

  leaves: TypedContractMethod<[leaf: BytesLike], [boolean], "view">;

  withdrawalCountForAmount: TypedContractMethod<
    [amount: BigNumberish],
    [bigint],
    "view"
  >;

  withdrawals: TypedContractMethod<
    [withdrawalKey: BytesLike],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "depositCountForAmount"
  ): TypedContractMethod<[amount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "leaves"
  ): TypedContractMethod<[leaf: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "withdrawalCountForAmount"
  ): TypedContractMethod<[amount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawals"
  ): TypedContractMethod<[withdrawalKey: BytesLike], [bigint], "view">;

  filters: {};
}
