/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PythStructs {
  export type PriceStruct = {
    price: BigNumberish;
    conf: BigNumberish;
    expo: BigNumberish;
    publishTime: BigNumberish;
  };

  export type PriceStructOutput = [
    price: bigint,
    conf: bigint,
    expo: bigint,
    publishTime: bigint
  ] & { price: bigint; conf: bigint; expo: bigint; publishTime: bigint };
}

export declare namespace ISwapper {
  export type SwapParamsStruct = {
    assetToSwapToOrFrom: AddressLike;
    amountToSwapToOrFrom: BigNumberish;
    receiver: AddressLike;
    updateData: BytesLike[];
  };

  export type SwapParamsStructOutput = [
    assetToSwapToOrFrom: string,
    amountToSwapToOrFrom: bigint,
    receiver: string,
    updateData: string[]
  ] & {
    assetToSwapToOrFrom: string;
    amountToSwapToOrFrom: bigint;
    receiver: string;
    updateData: string[];
  };
}

export interface SwapperInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "AGE"
      | "DENOMINATION"
      | "ORACLE_REGISTRY"
      | "PYTH"
      | "allowance"
      | "approve"
      | "balanceOf"
      | "chainStables"
      | "decimals"
      | "getOracleUpdateFee"
      | "getPrice"
      | "name"
      | "swapFromPrivateToken"
      | "swapToPrivateToken"
      | "symbol"
      | "totalSupply"
      | "transfer"
      | "transferFrom"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "AGE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "DENOMINATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ORACLE_REGISTRY",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "PYTH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "allowance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "chainStables",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getOracleUpdateFee",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(functionFragment: "getPrice", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "swapFromPrivateToken",
    values: [ISwapper.SwapParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "swapToPrivateToken",
    values: [ISwapper.SwapParamsStruct]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "AGE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DENOMINATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ORACLE_REGISTRY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "PYTH", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "chainStables",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOracleUpdateFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapFromPrivateToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapToPrivateToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
}

export interface Swapper extends BaseContract {
  connect(runner?: ContractRunner | null): Swapper;
  waitForDeployment(): Promise<this>;

  interface: SwapperInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  AGE: TypedContractMethod<[], [bigint], "view">;

  DENOMINATION: TypedContractMethod<[], [bigint], "view">;

  ORACLE_REGISTRY: TypedContractMethod<[], [string], "view">;

  PYTH: TypedContractMethod<[], [string], "view">;

  allowance: TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;

  approve: TypedContractMethod<
    [spender: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  chainStables: TypedContractMethod<[stable: AddressLike], [boolean], "view">;

  decimals: TypedContractMethod<[], [bigint], "view">;

  getOracleUpdateFee: TypedContractMethod<
    [updateData: BytesLike[]],
    [bigint],
    "view"
  >;

  getPrice: TypedContractMethod<
    [priceFeedId: BytesLike],
    [PythStructs.PriceStructOutput],
    "view"
  >;

  name: TypedContractMethod<[], [string], "view">;

  swapFromPrivateToken: TypedContractMethod<
    [swapParams: ISwapper.SwapParamsStruct],
    [void],
    "payable"
  >;

  swapToPrivateToken: TypedContractMethod<
    [swapParams: ISwapper.SwapParamsStruct],
    [void],
    "payable"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  transfer: TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "AGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DENOMINATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ORACLE_REGISTRY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PYTH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "allowance"
  ): TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [spender: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "chainStables"
  ): TypedContractMethod<[stable: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getOracleUpdateFee"
  ): TypedContractMethod<[updateData: BytesLike[]], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPrice"
  ): TypedContractMethod<
    [priceFeedId: BytesLike],
    [PythStructs.PriceStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "swapFromPrivateToken"
  ): TypedContractMethod<
    [swapParams: ISwapper.SwapParamsStruct],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "swapToPrivateToken"
  ): TypedContractMethod<
    [swapParams: ISwapper.SwapParamsStruct],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  filters: {};
}
