/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockSilentErc20Sol from "./MockSilentERC20.sol";
export type { mockSilentErc20Sol };
export type { MockERC20 } from "./MockERC20";
