/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IOracleRegistry,
  IOracleRegistryInterface,
} from "../../../src/interfaces/IOracleRegistry";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "asset",
            type: "address",
          },
          {
            internalType: "bytes32",
            name: "priceFeedId",
            type: "bytes32",
          },
        ],
        internalType: "struct IOracleRegistry.OracleParams",
        name: "oracleParams",
        type: "tuple",
      },
    ],
    name: "addAssetOracle",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "removeAssetOracle",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IOracleRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IOracleRegistryInterface {
    return new Interface(_abi) as IOracleRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IOracleRegistry {
    return new Contract(address, _abi, runner) as unknown as IOracleRegistry;
  }
}
