/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISwapper,
  ISwapperInterface,
} from "../../../src/interfaces/ISwapper";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes[]",
        name: "priceUpdate",
        type: "bytes[]",
      },
    ],
    name: "getOracleUpdateFee",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "assetToSwapToOrFrom",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "amountToSwapToOrFrom",
            type: "uint256",
          },
        ],
        internalType: "struct ISwapper.SwapParams",
        name: "swapParams",
        type: "tuple",
      },
    ],
    name: "swapFromPrivateToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "assetToSwapToOrFrom",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "amountToSwapToOrFrom",
            type: "uint256",
          },
        ],
        internalType: "struct ISwapper.SwapParams",
        name: "swapParams",
        type: "tuple",
      },
    ],
    name: "swapToPrivateToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISwapper__factory {
  static readonly abi = _abi;
  static createInterface(): ISwapperInterface {
    return new Interface(_abi) as ISwapperInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ISwapper {
    return new Contract(address, _abi, runner) as unknown as ISwapper;
  }
}
