/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ISilentERC20 } from "./ISilentERC20";
export type { ISilentERC20Metadata } from "./ISilentERC20Metadata";
export type { SilentERC20 } from "./SilentERC20";
