/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IOracleRegistry {
  export type OracleParamsStruct = {
    asset: AddressLike;
    priceFeedId: BytesLike;
  };

  export type OracleParamsStructOutput = [
    asset: string,
    priceFeedId: string
  ] & { asset: string; priceFeedId: string };
}

export interface IOracleRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addAssetPriceFeeds"
      | "getPriceFeed"
      | "removeAssetPriceFeeds"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addAssetPriceFeeds",
    values: [IOracleRegistry.OracleParamsStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getPriceFeed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAssetPriceFeeds",
    values: [AddressLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "addAssetPriceFeeds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPriceFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAssetPriceFeeds",
    data: BytesLike
  ): Result;
}

export interface IOracleRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IOracleRegistry;
  waitForDeployment(): Promise<this>;

  interface: IOracleRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addAssetPriceFeeds: TypedContractMethod<
    [oracleParams: IOracleRegistry.OracleParamsStruct[]],
    [void],
    "nonpayable"
  >;

  getPriceFeed: TypedContractMethod<[asset: AddressLike], [string], "view">;

  removeAssetPriceFeeds: TypedContractMethod<
    [assets: AddressLike[]],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addAssetPriceFeeds"
  ): TypedContractMethod<
    [oracleParams: IOracleRegistry.OracleParamsStruct[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getPriceFeed"
  ): TypedContractMethod<[asset: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "removeAssetPriceFeeds"
  ): TypedContractMethod<[assets: AddressLike[]], [void], "nonpayable">;

  filters: {};
}
