/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ISwapper {
  export type SwapParamsStruct = {
    assetToSwapToOrFrom: AddressLike;
    amountToSwapToOrFrom: BigNumberish;
    receiver: AddressLike;
    updateData: BytesLike[];
  };

  export type SwapParamsStructOutput = [
    assetToSwapToOrFrom: string,
    amountToSwapToOrFrom: bigint,
    receiver: string,
    updateData: string[]
  ] & {
    assetToSwapToOrFrom: string;
    amountToSwapToOrFrom: bigint;
    receiver: string;
    updateData: string[];
  };
}

export interface ISwapperInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getOracleUpdateFee"
      | "swapFromPrivateToken"
      | "swapToPrivateToken"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getOracleUpdateFee",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "swapFromPrivateToken",
    values: [ISwapper.SwapParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "swapToPrivateToken",
    values: [ISwapper.SwapParamsStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "getOracleUpdateFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapFromPrivateToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapToPrivateToken",
    data: BytesLike
  ): Result;
}

export interface ISwapper extends BaseContract {
  connect(runner?: ContractRunner | null): ISwapper;
  waitForDeployment(): Promise<this>;

  interface: ISwapperInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getOracleUpdateFee: TypedContractMethod<
    [priceUpdate: BytesLike[]],
    [bigint],
    "view"
  >;

  swapFromPrivateToken: TypedContractMethod<
    [swapParams: ISwapper.SwapParamsStruct],
    [void],
    "payable"
  >;

  swapToPrivateToken: TypedContractMethod<
    [swapParams: ISwapper.SwapParamsStruct],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getOracleUpdateFee"
  ): TypedContractMethod<[priceUpdate: BytesLike[]], [bigint], "view">;
  getFunction(
    nameOrSignature: "swapFromPrivateToken"
  ): TypedContractMethod<
    [swapParams: ISwapper.SwapParamsStruct],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "swapToPrivateToken"
  ): TypedContractMethod<
    [swapParams: ISwapper.SwapParamsStruct],
    [void],
    "payable"
  >;

  filters: {};
}
